# Generated by Django 4.1.6 on 2023-04-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcommsapp', '0013_alter_userprofile_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='middle_name',
        ),
    ]
