# Generated by Django 4.1.6 on 2023-04-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcommsapp', '0016_alter_userprofile_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
