# Generated by Django 4.2.6 on 2023-11-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderapp', '0019_rename_blog_post_post_code_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
    ]
