# Generated by Django 4.2.6 on 2023-11-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coderapp", "0020_remove_userprofile_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
